name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    environment:
      MAKEFLAGS: -j4 __all__/VERSION=latest

    steps:
    - uses: actions/checkout@v4

    - checkout
      - name: Build Binaries
        run: mkdir artifacts
        run: make ARCH=x86-64       PREFIX=/opt/openssh
        run: mv   bin/*             artifacts/openssh-x86-64.tgz
        run: make switch-toolchain
        run: make ARCH=armv7-eabihf PREFIX=/opt/openssh
        run: mv   bin/*             artifacts/openssh-armv7-eabihf.tgz
        run: make dirclean
        run: make ARCH=armv7-eabihf PREFIX=/system/opt/openssh
        run: mv   bin/*             artifacts/openssh-armv7-eabihf-android.tgz
        run: make switch-toolchain
        run: make ARCH=aarch64      PREFIX=/opt/openssh
        run: mv   bin/*             artifacts/openssh-aarch64.tgz
        run: make dirclean
        run: make ARCH=aarch64      PREFIX=/system/opt/openssh
        run: mv   bin/*             artifacts/openssh-aarch64-android.tgz
        store_artifacts:
          path: artifacts/
